# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'menu2_ui.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCommandLinkButton, QFrame, QGridLayout,
    QGroupBox, QLabel, QLineEdit, QPushButton,
    QRadioButton, QSizePolicy, QStackedWidget, QToolBox,
    QVBoxLayout, QWidget)

class Ui_Menu(object):
    def setupUi(self, Menu):
        if not Menu.objectName():
            Menu.setObjectName(u"Menu")
        Menu.resize(687, 520)
        Menu.setStyleSheet(u"background-color: rgb(0, 142, 255);")
        self.gridLayout_2 = QGridLayout(Menu)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_5 = QGridLayout()
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.toolBox = QToolBox(Menu)
        self.toolBox.setObjectName(u"toolBox")
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QSize(210, 500))
        self.toolBox.setMaximumSize(QSize(200, 16777215))
        self.toolBox.setCursor(QCursor(Qt.ArrowCursor))
        self.toolBox.setStyleSheet(u"background-color: rgb(0, 142, 255); color: rgb(255, 255, 255); font: 700 14pt \"Yu Gothic UI\";")
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.page.setGeometry(QRect(0, 0, 210, 380))
        self.page.setMinimumSize(QSize(0, 40))
        self.verticalLayout = QVBoxLayout(self.page)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalGroupBox = QGroupBox(self.page)
        self.verticalGroupBox.setObjectName(u"verticalGroupBox")
        sizePolicy.setHeightForWidth(self.verticalGroupBox.sizePolicy().hasHeightForWidth())
        self.verticalGroupBox.setSizePolicy(sizePolicy)
        self.verticalGroupBox.setMinimumSize(QSize(210, 0))
        self.verticalGroupBox.setStyleSheet(u"background-color: rgb(255, 255, 255); color: rgb(0, 142, 255);")
        self.verticalLayout_2 = QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.expo_Img_Button = QCommandLinkButton(self.verticalGroupBox)
        self.expo_Img_Button.setObjectName(u"expo_Img_Button")
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Minimum)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.expo_Img_Button.sizePolicy().hasHeightForWidth())
        self.expo_Img_Button.setSizePolicy(sizePolicy1)
        self.expo_Img_Button.setMinimumSize(QSize(198, 0))
        self.expo_Img_Button.setMaximumSize(QSize(16777215, 50))
        self.expo_Img_Button.setCursor(QCursor(Qt.PointingHandCursor))
        self.expo_Img_Button.setStyleSheet(u"QCommandLinkButton {font: 11pt \"Segoe UI\"; } QCommandLinkButton:checked {background-color: rgb(0, 166, 237);color: white; }")
        self.expo_Img_Button.setCheckable(True)

        self.verticalLayout_2.addWidget(self.expo_Img_Button)

        self.expo_pg_Button = QCommandLinkButton(self.verticalGroupBox)
        self.expo_pg_Button.setObjectName(u"expo_pg_Button")
        sizePolicy1.setHeightForWidth(self.expo_pg_Button.sizePolicy().hasHeightForWidth())
        self.expo_pg_Button.setSizePolicy(sizePolicy1)
        self.expo_pg_Button.setMinimumSize(QSize(198, 0))
        self.expo_pg_Button.setMaximumSize(QSize(16777215, 50))
        self.expo_pg_Button.setCursor(QCursor(Qt.PointingHandCursor))
        self.expo_pg_Button.setStyleSheet(u"QCommandLinkButton {font: 11pt \"Segoe UI\"; } QCommandLinkButton:checked {background-color: rgb(0, 166, 237);color: white; }")
        self.expo_pg_Button.setCheckable(True)

        self.verticalLayout_2.addWidget(self.expo_pg_Button, 0, Qt.AlignTop)


        self.verticalLayout.addWidget(self.verticalGroupBox)

        self.toolBox.addItem(self.page, u"Exportar P\u00e1gina")
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.page_2.setGeometry(QRect(0, 0, 210, 380))
        sizePolicy2 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.page_2.sizePolicy().hasHeightForWidth())
        self.page_2.setSizePolicy(sizePolicy2)
        self.verticalGroupBox_2 = QGroupBox(self.page_2)
        self.verticalGroupBox_2.setObjectName(u"verticalGroupBox_2")
        self.verticalGroupBox_2.setGeometry(QRect(0, 0, 210, 494))
        sizePolicy2.setHeightForWidth(self.verticalGroupBox_2.sizePolicy().hasHeightForWidth())
        self.verticalGroupBox_2.setSizePolicy(sizePolicy2)
        self.verticalGroupBox_2.setMinimumSize(QSize(210, 0))
        self.verticalGroupBox_2.setStyleSheet(u"background-color: rgb(255, 255, 255); color: rgb(0, 142, 255);")
        self.verticalLayout_4 = QVBoxLayout(self.verticalGroupBox_2)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.pdf_to_word = QCommandLinkButton(self.verticalGroupBox_2)
        self.pdf_to_word.setObjectName(u"pdf_to_word")
        sizePolicy1.setHeightForWidth(self.pdf_to_word.sizePolicy().hasHeightForWidth())
        self.pdf_to_word.setSizePolicy(sizePolicy1)
        self.pdf_to_word.setMinimumSize(QSize(198, 0))
        self.pdf_to_word.setMaximumSize(QSize(16777215, 50))
        self.pdf_to_word.setCursor(QCursor(Qt.PointingHandCursor))
        self.pdf_to_word.setStyleSheet(u"QCommandLinkButton {font: 11pt \"Segoe UI\"; } QCommandLinkButton:checked {background-color: rgb(0, 166, 237);color: white; }")
        self.pdf_to_word.setCheckable(True)

        self.verticalLayout_4.addWidget(self.pdf_to_word)

        self.pdf_to_excel = QCommandLinkButton(self.verticalGroupBox_2)
        self.pdf_to_excel.setObjectName(u"pdf_to_excel")
        sizePolicy1.setHeightForWidth(self.pdf_to_excel.sizePolicy().hasHeightForWidth())
        self.pdf_to_excel.setSizePolicy(sizePolicy1)
        self.pdf_to_excel.setMinimumSize(QSize(198, 0))
        self.pdf_to_excel.setMaximumSize(QSize(16777215, 50))
        self.pdf_to_excel.setCursor(QCursor(Qt.PointingHandCursor))
        self.pdf_to_excel.setStyleSheet(u"QCommandLinkButton {font: 11pt \"Segoe UI\"; } QCommandLinkButton:checked {background-color: rgb(0, 166, 237);color: white; }")
        self.pdf_to_excel.setCheckable(True)

        self.verticalLayout_4.addWidget(self.pdf_to_excel)

        self.word_to_pdf = QCommandLinkButton(self.verticalGroupBox_2)
        self.word_to_pdf.setObjectName(u"word_to_pdf")
        sizePolicy1.setHeightForWidth(self.word_to_pdf.sizePolicy().hasHeightForWidth())
        self.word_to_pdf.setSizePolicy(sizePolicy1)
        self.word_to_pdf.setMinimumSize(QSize(198, 0))
        self.word_to_pdf.setMaximumSize(QSize(16777215, 50))
        self.word_to_pdf.setCursor(QCursor(Qt.PointingHandCursor))
        self.word_to_pdf.setStyleSheet(u"QCommandLinkButton {font: 11pt \"Segoe UI\"; } QCommandLinkButton:checked {background-color: rgb(0, 166, 237);color: white; }")
        self.word_to_pdf.setCheckable(True)

        self.verticalLayout_4.addWidget(self.word_to_pdf)

        self.excel_to_pdf = QCommandLinkButton(self.verticalGroupBox_2)
        self.excel_to_pdf.setObjectName(u"excel_to_pdf")
        sizePolicy1.setHeightForWidth(self.excel_to_pdf.sizePolicy().hasHeightForWidth())
        self.excel_to_pdf.setSizePolicy(sizePolicy1)
        self.excel_to_pdf.setMinimumSize(QSize(198, 0))
        self.excel_to_pdf.setMaximumSize(QSize(16777215, 50))
        self.excel_to_pdf.setCursor(QCursor(Qt.PointingHandCursor))
        self.excel_to_pdf.setStyleSheet(u"QCommandLinkButton {font: 11pt \"Segoe UI\"; } QCommandLinkButton:checked {background-color: rgb(0, 166, 237);color: white; }")
        self.excel_to_pdf.setCheckable(True)

        self.verticalLayout_4.addWidget(self.excel_to_pdf, 0, Qt.AlignTop)

        self.toolBox.addItem(self.page_2, u"Converter Arquivo")
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.verticalGroupBox_3 = QGroupBox(self.page_3)
        self.verticalGroupBox_3.setObjectName(u"verticalGroupBox_3")
        self.verticalGroupBox_3.setGeometry(QRect(0, 0, 210, 380))
        sizePolicy.setHeightForWidth(self.verticalGroupBox_3.sizePolicy().hasHeightForWidth())
        self.verticalGroupBox_3.setSizePolicy(sizePolicy)
        self.verticalGroupBox_3.setMinimumSize(QSize(210, 0))
        self.verticalGroupBox_3.setStyleSheet(u"background-color: rgb(255, 255, 255); color: rgb(0, 142, 255);")
        self.verticalLayout_3 = QVBoxLayout(self.verticalGroupBox_3)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.Add_page = QCommandLinkButton(self.verticalGroupBox_3)
        self.Add_page.setObjectName(u"Add_page")
        sizePolicy1.setHeightForWidth(self.Add_page.sizePolicy().hasHeightForWidth())
        self.Add_page.setSizePolicy(sizePolicy1)
        self.Add_page.setMinimumSize(QSize(198, 0))
        self.Add_page.setMaximumSize(QSize(16777215, 50))
        self.Add_page.setCursor(QCursor(Qt.PointingHandCursor))
        self.Add_page.setStyleSheet(u"QCommandLinkButton {font: 11pt \"Segoe UI\"; } QCommandLinkButton:checked {background-color: rgb(0, 166, 237);color: white; }")
        self.Add_page.setCheckable(True)

        self.verticalLayout_3.addWidget(self.Add_page)

        self.Delete_page = QCommandLinkButton(self.verticalGroupBox_3)
        self.Delete_page.setObjectName(u"Delete_page")
        sizePolicy1.setHeightForWidth(self.Delete_page.sizePolicy().hasHeightForWidth())
        self.Delete_page.setSizePolicy(sizePolicy1)
        self.Delete_page.setMinimumSize(QSize(198, 0))
        self.Delete_page.setMaximumSize(QSize(16777215, 50))
        self.Delete_page.setCursor(QCursor(Qt.PointingHandCursor))
        self.Delete_page.setStyleSheet(u"QCommandLinkButton {font: 11pt \"Segoe UI\"; } QCommandLinkButton:checked {background-color: rgb(0, 166, 237);color: white; }")
        self.Delete_page.setCheckable(True)

        self.verticalLayout_3.addWidget(self.Delete_page, 0, Qt.AlignTop)

        self.toolBox.addItem(self.page_3, u"Editar")

        self.gridLayout_5.addWidget(self.toolBox, 0, 0, 1, 1)

        self.frame = QFrame(Menu)
        self.frame.setObjectName(u"frame")
        self.frame.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.gridLayout = QGridLayout(self.frame)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4 = QGridLayout()
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.gridLayout_4.setHorizontalSpacing(10)
        self.gridLayout_4.setContentsMargins(2, 10, 2, 10)
        self.lineEdit = QLineEdit(self.frame)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setEnabled(False)
        sizePolicy3 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy3)
        self.lineEdit.setMinimumSize(QSize(270, 0))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(245, 245, 245, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(0, 0, 0, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.lineEdit.setPalette(palette)
        self.lineEdit.setStyleSheet(u"background-color: rgb(245, 245, 245);")

        self.gridLayout_4.addWidget(self.lineEdit, 0, 0, 1, 1)

        self.buscar_Button = QPushButton(self.frame)
        self.buscar_Button.setObjectName(u"buscar_Button")
        sizePolicy4 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.buscar_Button.sizePolicy().hasHeightForWidth())
        self.buscar_Button.setSizePolicy(sizePolicy4)
        self.buscar_Button.setMinimumSize(QSize(0, 30))
        self.buscar_Button.setCursor(QCursor(Qt.PointingHandCursor))
        self.buscar_Button.setStyleSheet(u"background-color: rgb(0, 166, 237); color: rgb(255, 255, 255); font: 700 9pt \"Segoe UI\";")

        self.gridLayout_4.addWidget(self.buscar_Button, 0, 1, 1, 1)

        self.limpar_Button = QPushButton(self.frame)
        self.limpar_Button.setObjectName(u"limpar_Button")
        sizePolicy4.setHeightForWidth(self.limpar_Button.sizePolicy().hasHeightForWidth())
        self.limpar_Button.setSizePolicy(sizePolicy4)
        self.limpar_Button.setMinimumSize(QSize(0, 30))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush3 = QBrush(QColor(0, 166, 237, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush3)
        brush4 = QBrush(QColor(255, 255, 255, 128))
        brush4.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush4)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush4)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush4)
#endif
        self.limpar_Button.setPalette(palette1)
        self.limpar_Button.setCursor(QCursor(Qt.PointingHandCursor))
        self.limpar_Button.setStyleSheet(u"background-color: rgb(0, 166, 237); color: rgb(255, 255, 255); font: 700 9pt \"Segoe UI\";")

        self.gridLayout_4.addWidget(self.limpar_Button, 0, 2, 1, 1)


        self.gridLayout.addLayout(self.gridLayout_4, 3, 0, 1, 1)

        self.gridLayout_6 = QGridLayout()
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.stackedWidget = QStackedWidget(self.frame)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setStyleSheet(u"background-color: rgb(0, 142, 255);")
        self.page_n_pages = QWidget()
        self.page_n_pages.setObjectName(u"page_n_pages")
        self.pages_Edit = QLineEdit(self.page_n_pages)
        self.pages_Edit.setObjectName(u"pages_Edit")
        self.pages_Edit.setGeometry(QRect(80, 160, 321, 31))
        sizePolicy3.setHeightForWidth(self.pages_Edit.sizePolicy().hasHeightForWidth())
        self.pages_Edit.setSizePolicy(sizePolicy3)
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.Button, brush)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush)
        self.pages_Edit.setPalette(palette2)
        self.pages_Edit.setStyleSheet(u"background-color: rgb(255, 255, 255); font: 11pt \"Segoe UI\";")
        self.ate_Edit = QLineEdit(self.page_n_pages)
        self.ate_Edit.setObjectName(u"ate_Edit")
        self.ate_Edit.setGeometry(QRect(251, 90, 151, 31))
        sizePolicy4.setHeightForWidth(self.ate_Edit.sizePolicy().hasHeightForWidth())
        self.ate_Edit.setSizePolicy(sizePolicy4)
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.Button, brush)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush)
        self.ate_Edit.setPalette(palette3)
        self.ate_Edit.setStyleSheet(u"background-color: rgb(255, 255, 255); font: 11pt \"Segoe UI\";")
        self.de_ate_radioButton = QRadioButton(self.page_n_pages)
        self.de_ate_radioButton.setObjectName(u"de_ate_radioButton")
        self.de_ate_radioButton.setGeometry(QRect(80, 64, 81, 20))
        self.de_ate_radioButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.de_ate_radioButton.setStyleSheet(u"color: rgb(255, 255, 255); font: 700 10pt \"Segoe UI\";")
        self.de_Edit = QLineEdit(self.page_n_pages)
        self.de_Edit.setObjectName(u"de_Edit")
        self.de_Edit.setGeometry(QRect(80, 90, 151, 31))
        sizePolicy4.setHeightForWidth(self.de_Edit.sizePolicy().hasHeightForWidth())
        self.de_Edit.setSizePolicy(sizePolicy4)
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.Button, brush)
        palette4.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette4.setBrush(QPalette.Active, QPalette.Base, brush)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush)
        self.de_Edit.setPalette(palette4)
        self.de_Edit.setStyleSheet(u"background-color: rgb(255, 255, 255); font: 11pt \"Segoe UI\";")
        self.pages_radioButton = QRadioButton(self.page_n_pages)
        self.pages_radioButton.setObjectName(u"pages_radioButton")
        self.pages_radioButton.setGeometry(QRect(80, 135, 131, 20))
        sizePolicy4.setHeightForWidth(self.pages_radioButton.sizePolicy().hasHeightForWidth())
        self.pages_radioButton.setSizePolicy(sizePolicy4)
        self.pages_radioButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.pages_radioButton.setStyleSheet(u"color: rgb(255, 255, 255); font: 700 10pt \"Segoe UI\";")
        self.stackedWidget.addWidget(self.page_n_pages)
        self.page_6 = QWidget()
        self.page_6.setObjectName(u"page_6")
        self.stackedWidget.addWidget(self.page_6)

        self.gridLayout_6.addWidget(self.stackedWidget, 0, 0, 1, 1)


        self.gridLayout.addLayout(self.gridLayout_6, 4, 0, 1, 1)

        self.verticalWidget = QWidget(self.frame)
        self.verticalWidget.setObjectName(u"verticalWidget")
        self.verticalWidget.setStyleSheet(u"background-color: rgb(0, 142, 255);")
        self.verticalLayout_5 = QVBoxLayout(self.verticalWidget)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(-1, -1, -1, 5)
        self.label = QLabel(self.verticalWidget)
        self.label.setObjectName(u"label")
        self.label.setStyleSheet(u"color: rgb(255, 255, 255); background-color: rgb(0, 142, 255); font: 700 60pt \"Segoe UI Variable Display\";")

        self.verticalLayout_5.addWidget(self.label, 0, Qt.AlignHCenter)


        self.gridLayout.addWidget(self.verticalWidget, 1, 0, 1, 1)

        self.verticalLayout_6 = QVBoxLayout()
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(-1, 5, 5, 5)
        self.confirm_Button = QPushButton(self.frame)
        self.confirm_Button.setObjectName(u"confirm_Button")
        self.confirm_Button.setEnabled(True)
        sizePolicy4.setHeightForWidth(self.confirm_Button.sizePolicy().hasHeightForWidth())
        self.confirm_Button.setSizePolicy(sizePolicy4)
        self.confirm_Button.setMinimumSize(QSize(0, 30))
        self.confirm_Button.setCursor(QCursor(Qt.PointingHandCursor))
        self.confirm_Button.setLayoutDirection(Qt.LeftToRight)
        self.confirm_Button.setStyleSheet(u"background-color: rgb(0, 166, 237); color: rgb(255, 255, 255); font: 700 9pt \"Segoe UI\";")
        self.confirm_Button.setAutoRepeatInterval(101)

        self.verticalLayout_6.addWidget(self.confirm_Button, 0, Qt.AlignRight)


        self.gridLayout.addLayout(self.verticalLayout_6, 5, 0, 1, 1)


        self.gridLayout_5.addWidget(self.frame, 0, 1, 1, 1)


        self.gridLayout_2.addLayout(self.gridLayout_5, 0, 0, 1, 1)


        self.retranslateUi(Menu)

        self.toolBox.setCurrentIndex(2)
        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Menu)
    # setupUi

    def retranslateUi(self, Menu):
        Menu.setWindowTitle(QCoreApplication.translate("Menu", u"Menu", None))
        Menu.setWindowFilePath("")
        self.expo_Img_Button.setText(QCoreApplication.translate("Menu", u"Como Imagem", None))
        self.expo_pg_Button.setText(QCoreApplication.translate("Menu", u"Como PDF", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QCoreApplication.translate("Menu", u"Exportar P\u00e1gina", None))
        self.pdf_to_word.setText(QCoreApplication.translate("Menu", u"PDF  >>  Word", None))
        self.pdf_to_excel.setText(QCoreApplication.translate("Menu", u"PDF  >>  Excel", None))
        self.word_to_pdf.setText(QCoreApplication.translate("Menu", u"Word  >>  PDF", None))
        self.excel_to_pdf.setText(QCoreApplication.translate("Menu", u"Excel  >>  PDF", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QCoreApplication.translate("Menu", u"Converter Arquivo", None))
        self.Add_page.setText(QCoreApplication.translate("Menu", u"Combinar Arquivos", None))
        self.Delete_page.setText(QCoreApplication.translate("Menu", u"Remover P\u00e1gina", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), QCoreApplication.translate("Menu", u"Editar", None))
        self.lineEdit.setPlaceholderText(QCoreApplication.translate("Menu", u"Aguardando arquivo", None))
        self.buscar_Button.setText(QCoreApplication.translate("Menu", u"Buscar", None))
        self.limpar_Button.setText(QCoreApplication.translate("Menu", u"Limpar", None))
        self.pages_Edit.setPlaceholderText(QCoreApplication.translate("Menu", u"Utilizando tra\u00e7o (-) entre os n\u00fameros", None))
        self.ate_Edit.setPlaceholderText(QCoreApplication.translate("Menu", u"at\u00e9", None))
        self.de_ate_radioButton.setText(QCoreApplication.translate("Menu", u"De / At\u00e9", None))
        self.de_Edit.setPlaceholderText(QCoreApplication.translate("Menu", u"de", None))
        self.pages_radioButton.setText(QCoreApplication.translate("Menu", u"Informar p\u00e1ginas", None))
        self.label.setText(QCoreApplication.translate("Menu", u"PDF_Export", None))
        self.confirm_Button.setText(QCoreApplication.translate("Menu", u"Confirmar >>", None))
    # retranslateUi

